### ISSUE TITLE
Duda sobre la obtención de los parámetros

### ISSUE THREAD

**Issue by alfredorguezz** [Bimo99B9/autoUniCalendar#5]
Muy buenas Daniel,
En primer lugar, comentarte que tu programa me parece una gran idea para organizar las asignaturas, gracias por compartirlo.
La única duda que me surge es en la obtención de los parámetros JSESSIONID y oam.Flash.RENDERMAP.TOKEN . Mi navegador predeterminado es el Chrome, puede que sea ese el problema, la cosa está en que no soy capaz de encontrar esos datos.
Si me pudieras decir cómo encontrarlos de una manera más detallada te lo agradecería.
Un saludo.

**Comment by miermontoto** [comment]
hey, para Chrome:

- inicia sesión como lo harías normalmente en el [SIES](https://sies.uniovi.es/serviciosacademicos/web/servicios/servicios.faces)
- una vez dentro, pulsa F12 o Ctrl+Shift+I, aparecerá un menú nuevo en pantalla: 
![image](https://user-images.githubusercontent.com/20926603/188656827-0207f095-c3e3-4aed-bf0a-8e39e32006c3.png)
- una vez dentro, navega hasta el submenú "Application" y dentro "Cookies" y selecciona la página del SIES, como aparece en la imagen: ![image](https://github.com/Bimo99B9/autoUniCalendar/blob/main/assets/cookies.jpg?raw=true)
- desde aquí, copia las cookies 'JSESSIONID' y 'oam.FlashRENDERMAP' dentro de sus correspondientes casillas.

ten en cuenta que algunos grados todavía no tienen los grupos cerrados y, por lo tanto, no hay eventos que descargar.

**Comment by Bimo99B9** [comment]
Gracias @miermontoto por la ayuda. 
A la aclaración me gustaría añadir el [vídeo que publiqué en Twitter](https://twitter.com/Bimo99B9/status/1565961729074675712?s=20&t=Vh5fkAaLsMsXsMBkhV-6aw9), donde se ve el proceso de copiarlas desde el panel de Chrome a la aplicación, y descargar el calendario. Espero que te ayude, si necesitas algo más reabre el issue sin problema.

Un saludo.
