### ISSUE TITLE
Descarga el calendario del año pasado.

### ISSUE THREAD

**Issue by Kintanes** [Bimo99B9/autoUniCalendar#9]
He utilizado el script el día de hoy para obtener el CSV del calendario de este curso y funciona todo perfectamente, salvo por el hecho de que me obtiene el CSV del horario del año pasado. No tengo idea de que hacer y me encantaría poder solucionar este problema.
Muchas gracias.

**Comment by cyberrb25** [comment]
Porque todavía no han puesto el horario del nuevo año, hasta donde he visto. Sigue marcado el del año pasado.

Yo ahora mismo estoy montando a manopla lo que se de la asignatura que me han abierto. Y si para el lunes no está, no me quedará otra que montar el resto de asignaturas con el Bulk Editor...

**Comment by Bimo99B9** [comment]
Buenas @cyberrb25 @Kintanes , en los últimos commits añadí la posibilidad de escoger las fechas del calendario a descargar, ahora mismo no recuerdo si lo añadí también en el script y dejé por default las fechas del año pasado (estoy de viaje hasta el lunes y no puedo revisarlo), pero en la versión web (https://autounicalendar.onrender.com/) estoy bastante seguro de que por defecto están las fechas de este nuevo curso.

 Echadle un vistazo y me decís, gracias por avisar!

**Comment by Kintanes** [comment]
En el enlace si que funciona, muchas gracias de verdad.

**Comment by cyberrb25** [comment]
No sé cuándo han metido los horarios, pero creo que de mañana cuando me llegó el primer correo de un profesor todavía no estaban. Más que nada porque, a la vista de ello, me puse a montar en un editor de eventos de calendario uno a mano para evitar perderme clase. No he probado el script ahora, pero.

**Comment by Bimo99B9** [comment]
Agregado: Parámetros para fechas de inicio y fin en el script. Si no se proveen, se usa fechas predeterminadas del curso 2023-2024.

Uso:
python3 autoUniCalendar.py <JSESSIONID> [FECHA_INICIO] [FECHA_FIN]

Ejemplo:
python3 autoUniCalendar.py ABC123 01/09/2023 01/07/2024
